services:
  redis:
    image: redis:8
    container_name: docker_local_redis
    ports:
      - "6379:6379"
    volumes:
      - backend_system_redis_data:/data
    

  postgres:
    image: postgres:18-alpine
    container_name: docker_local_postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5433:5432"

    volumes:
      - backend_system_postgres_data:/var/lib/postgresql # <-- Change this line
  

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    

volumes:
  backend_system_postgres_data:
  backend_system_redis_data: # <-- we can add a volume for redis data persistence if needed
  backend_system_kafka_data: # <-- we can add a volume for kafka data persistence if needed
  backend_system_zookeeper_data: # <-- we can add a volume for zookeeper data persistence if needed