services:
  redis:
    image: redis:8
    container_name: docker_local_redis
    ports:
      - "6379:6379"
    volumes:
      - backend_system_redis_data:/data
    

  postgres:
    image: postgres:18-alpine
    container_name: docker_local_postgres

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5433:5432"

    volumes:
      - backend_system_postgres_data:/var/lib/postgresql # <-- Change this line

volumes:
  backend_system_postgres_data:
  backend_system_redis_data: # <-- we can add a volume for redis data persistence if needed